# *Tweetify*: Mapping the Intersection of Twitter and Spotify

# Data Collection and Preprocessing

## Datasets

### Twitter Datasets
- [x] 2022 Twitter Dataset `open.spotify.com/track` AND `#popmusic`
	- `2022-tweet-data.csv`
- [x] 2021 Twitter Dataset `open.spotify.com/track` AND `#popmusic`
	- `2021-tweet-data.csv`
- [x] 2020 Twitter Dataset `open.spotify.com/track` AND `#popmusic`
	- `2020-tweet-data.csv`

### Twitter Audio Features 
- [x] 2022 Twitter Audio Features `open.spotify.com/track` AND `#popmusic`
	- `2022-tweet-audio-feat.csv`
- [x] 2021 Twitter Audio Features `open.spotify.com/track` AND `#popmusic`
	- `2021-tweet-audio-feat.csv`
- [x] 2020 Twitter Audio Features`open.spotify.com/track` AND `#popmusic`
	- `2020-tweet-audio-feat.csv`
	
### Billboard Top 100 Datasets
- [x] 2022 Billboard Top 100 Songs 
	- `2022-billboard-t100-songs.csv`
- [ ] 2021 Billboard Top 100 Songs
	- `2021-billboard-t100-songs.csv`
- [ ] 2020 Billboard Top 100 Songs
	- `2021-billboard-t100-songs.csv`
	
### Billboard Top 100 Audio Features 
- [x] 2022 Billboard Top 100 Songs Audio Features 
	- `2022-billboard-t100-audio-feat.csv`
- [ ] 2021 Billboard Top 100 Songs Audio Features 
	- `2021-billboard-t100-audio-feat.csv`
- [ ] 2020 Billboard Top 100 Songs Audio Features 
	- `2020-billboard-t100-audio-feat.csv`

### Twitter Billboard Datasets 
- [x] 2022 Twitter Billboard `open.spotify.com/track` AND `#billboard`
	- `2022-tweet-billboard-data.csv`
- [x] 2021 Twitter Billboard `open.spotify.com/track` AND `#billboard`
	- `2021-tweet-billboard-data.csv`
- [x] 2020 Twitter Billboard `open.spotify.com/track` AND `#billboard`
	- `2020-tweet-billboard-data.csv`
	
### Twitter Billboard Audio Features
- [x] 2022 Twitter Billboard Audio Features `open.spotify.com/track` AND `#billboard`
	- `2022-tweet-billboard-audio-feat.csv`
- [x] 2021 Twitter Billboard Audio Features `open.spotify.com/track` AND `#billboard`
	- `2021-tweet-billboard-audio-feat.csv`
- [x] 2020 Twitter Billboard Audio Features `open.spotify.com/track` AND `#billboard`
	- `2020-tweet-billboard-audio-feat.csv`

## Tools

In [2]:
# importing libraries 
import snscrape.modules.twitter as sntwitter
import pandas as pd
import numpy as np

### Function to Scrape Tweets 
`def scrape_music_tweets(query, start_date, end_date, lang)`
- `query`: keywords used 
- `start_date`: beginning of search 
- `end_date`: ending of search 
- `lang`: language of tweets 

attributes used: 
- `id`: id of tweet 
- `user.username`: username of tweet
- `rawContent`: text content of tweet
- `date`: date tweet was created
- `lang`: language of tweet 
- `outlinks`: url(s) 
- `user.id`: id of user
- `user.followersCount`: user follower count
- `user.friendsCount`: user friend count 
- `user.location`: location of user
- `source`: where tweet was posted from 
- `retweetCount`: retweet count
- `replyCount`: reply count 
- `likeCount`: like count

In [3]:
def scrape_music_tweets(query, start_date, end_date, lang='en'):
    # create a list to store tweet data
    music_tweets = []

    # use TwitterSearchScraper to scrape data and append tweets to list
    for i, tweet in enumerate(sntwitter.TwitterSearchScraper(f'{query} since:{start_date} until:{end_date} lang:{lang}').get_items()): 
        music_tweets.append([
            tweet.id, # id of tweet 
            tweet.user.username, # username of tweet 
            tweet.rawContent, # text content of tweet
            tweet.date, # date tweet was created
            tweet.lang, # language of tweet 
            tweet.outlinks, # url(s)
            tweet.user.id, # id of user 
            tweet.user.followersCount, # num of followers user has 
            tweet.user.friendsCount, # num of friends user has 
            tweet.user.location, # location of user 
            tweet.source, # where tweet was posted from 
            tweet.retweetCount, # count of retweets
            tweet.replyCount, # count of replies
            tweet.likeCount, # count of likes 
        ])

    return music_tweets

### Function to Create Dataframe
`def music_def(music_tweets)`
- `music_tweets`:

In [4]:
def music_df(music_tweets):
    # define the column names for the DataFrame
    column_names = [
        'id_str', 
        'username', 
        'text', 
        'date', 
        'user_language', 
        'URLs', 
        'user_id',
        'followers_count',
        'friends_count',
        'user_location',
        'source_device',
        'retweet_count',
        'reply_count',
        'like_count',
    ]

    # create a DataFrame from the tweet list
    df = pd.DataFrame(music_tweets, columns=column_names)
    df.drop_duplicates(subset=['username'], inplace=True)

    return df

### Function to Remove Special/Misc Characters
`def clean_text(text)` 
- `text`:

In [5]:
# removing special characters from 'text' column for sentiment analyses 
import re

# links + special chars
link_pattern = re.compile(r'http\S+')
special_char = re.compile(r'[^\w\s\n]+')

def clean_text(text):
    # remove links
    text = re.sub(link_pattern, '', text)
    # remove special characters
    text = re.sub(special_char, '', text)
    text = re.sub(r'\s+', ' ', text)
    # convert to lowercase
    text = text.lower()
    return text

## 2022 Twitter Dataset 
**query:** `open.spotify.com/track` and `#popmusic`

**timeframe:** `since:2022-01-01` and `until:2022-12-31`

In [6]:
query = '(open.spotify.com/track AND #popmusic)'
start_date = '2022-01-01'
end_date = '2022-12-31'

music_2022 = scrape_music_tweets(query, start_date, end_date)
music_2022 = music_df(music_2022)

/var/folders/xj/q2hvgrs103gcrg_vkzc7m6vm0000gn/T/ipykernel_80590/4027346299.py:13: FutureWarning: outlinks is deprecated, use links (url attribute) instead
  tweet.outlinks, # url(s)

In [7]:
# removing special characters and dropping url duplicates
music_2022['text_clean'] = music_2022['text'].apply(clean_text)

In [8]:
# printing DataFrame
music_2022

,id_str,username,text,date,user_language,URLs,user_id,followers_count,friends_count,user_location,source_device,retweet_count,reply_count,like_count,text_clean
0,1608776592708472834,AlixEwartOffic,It would mean so so so much if you streamed so...,2022-12-30 10:46:43+00:00,en,[https://open.spotify.com/track/15fkXlD3aymzgP...,1523318377346912259,15,156,"England, United Kingdom","<a href=""http://twitter.com/download/iphone"" r...",0,0,1,it would mean so so so much if you streamed so...
1,1608776537096192001,xasherz2896,It would mean so so so much if you streamed so...,2022-12-30 10:46:30+00:00,en,[https://open.spotify.com/track/15fkXlD3aymzgP...,1602775863266779136,1,91,Your dads bed,"<a href=""http://twitter.com/download/iphone"" r...",0,0,1,it would mean so so so much if you streamed so...
2,1608455418853859329,TommyBlunt95,Alisun is an LA based artist very passionate a...,2022-12-29 13:30:30+00:00,en,[https://open.spotify.com/track/1rQVDh5AXwhRIe...,803945912271679488,34088,23587,"USA, UK, Australia & worldwide","<a href=""https://www.socialjukebox.com"" rel=""n...",0,0,1,alisun is an la based artist very passionate a...
3,1608195752240754688,carlosENVIRO,I love this one recorded at abbey Road Love is...,2022-12-28 20:18:40+00:00,en,[https://open.spotify.com/track/5BKEacx0Aqmv9n...,1584623909294465035,44,187,england,"<a href=""https://mobile.twitter.com"" rel=""nofo...",0,0,4,i love this one recorded at abbey road love is...
4,1607863016720048130,mickmarlowmusic,https://t.co/PUoa4Sqn9e Check out my latest si...,2022-12-27 22:16:30+00:00,en,[https://open.spotify.com/track/0cFgjiZiiFy7vu...,1475119112707878916,43,181,,"<a href=""http://twitter.com/download/iphone"" r...",1,1,3,check out my latest single smiling now for me...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1467,1480586004998336512,JulienceUK,"You've been waiting for it, and now it's here....",2022-01-10 17:03:06+00:00,en,[https://jubb.ly/4b0ba1],16613721,35387,16981,Manchester / Droylsden,"<a href=""https://www.ocoya.net"" rel=""nofollow""...",4,0,6,youve been waiting for it and now its here my ...
1470,1480217157250211843,jcesarmusic,Thank you so much to everyone who has listened...,2022-01-09 16:37:26+00:00,en,[https://spoti.fi/3F9T4YA],706997306,700,1483,"Paris, France","<a href=""https://mobile.twitter.com"" rel=""nofo...",0,1,3,thank you so much to everyone who has listened...
1473,1479628482309099522,MatthewSiqueir1,"Hello there! Just released my first single, ho...",2022-01-08 01:38:15+00:00,en,[https://open.spotify.com/track/4MwJM9RtlWhk5H...,1466241123278483459,1,4,,"<a href=""http://twitter.com/download/android"" ...",0,0,0,hello there just released my first single hope...
1477,1478778864977559557,kingbabajames,https://t.co/Kq0rLnozmF you say u love ❤ me no...,2022-01-05 17:22:10+00:00,en,[https://open.spotify.com/track/5HuOVYie8l7XIr...,126995619,2625,2160,DC/ NYC WORLDWIDE.,"<a href=""http://twitter.com/download/android"" ...",0,1,2,you say u love me now you left me why song ma...
1478,1478718947944013825,bastafari,Check out Flashpoint Runs and their new single...,2022-01-05 13:24:05+00:00,en,[https://open.spotify.com/track/7k1NfrcgO00RUf...,142265654,34,211,Behind you.,"<a href=""http://twitter.com/download/android"" ...",0,0,0,check out flashpoint runs and their new single...

In [ ]:
# saving DataFrame into .csv format
music_2022.to_csv('2022-tweet-data.csv', sep=',', index=False)

## 2021 Twitter Dataset 
**query:** `open.spotify.com/track` and `#popmusic`

**timeframe:** `since:2021-01-01` and `until:2021-12-31`

In [7]:
query = '(open.spotify.com/track AND #popmusic)'
start_date = '2021-01-01'
end_date = '2021-12-31'

music_2021 = scrape_music_tweets(query, start_date, end_date)
music_2021 = music_df(music_2021)

<ipython-input-2-5ca9bf2c3f71>:13: FutureWarning: outlinks is deprecated, use links (url attribute) instead
  tweet.outlinks, # url(s)

In [8]:
# removing special characters and dropping url duplicates
music_2021['text_clean'] = music_2021['text'].apply(clean_text)

In [ ]:
music_2021

In [ ]:
# saving DataFrame into .csv format
music_2021.to_csv('2021-tweet-data.csv', sep=',', index=False)

## 2020 Twitter Dataset 
**query:** `open.spotify.com/track` and `#popmusic`

**timeframe:** `since:2020-01-01` and `until:2020-12-31`

In [9]:
query = '(open.spotify.com/track AND #popmusic)'
start_date = '2020-01-01'
end_date = '2020-12-31'

music_2020 = scrape_music_tweets(query, start_date, end_date)
music_2020 = music_df(music_2020)

<ipython-input-2-5ca9bf2c3f71>:13: FutureWarning: outlinks is deprecated, use links (url attribute) instead
  tweet.outlinks, # url(s)

In [10]:
# removing special characters and dropping url duplicates
music_2020['text_clean'] = music_2020['text'].apply(clean_text)

In [ ]:
music_2020

In [ ]:
music_2020.to_csv('2020-tweet-data.csv', sep=',', index=False)

### Extracting Spotify URLs

In [11]:
def extract_spotify_urls(urls):
    return [url for url in urls if 'https://open.spotify.com/track' in url or 'https://spoti.fi/' in url]

### Extracting Tracks IDs from Spotify Links

In [12]:
import requests
import re

def extract_track_ids(df):
    # Create an empty list to store the track IDs
    track_ids = []

    # Iterate through each row in the data frame
    for i in range(df.shape[0]):
        row = df.iloc[i]
        # Iterate through each item in the list in the current row
        for link in row['spotify_URLs']:
            if "open.spotify.com/track/" in link:
                # Split the link on '/' and extract the track ID
                track_id = link.split('/')[-1]
                track_ids.append(track_id)
            elif "spoti.fi" in link:
                # Follow the redirection to the actual URL
                r = requests.get(link)
                if r.status_code == 200:
                    # Extract the track ID from the actual URL
                    pattern = r"/track/([a-zA-Z0-9]+)"
                    match = re.search(pattern, r.url)
                    if match:
                        track_id = match.group(1)
                        track_ids.append(track_id)

    # Create a new DataFrame with the unique track IDs
    tracks_df = pd.DataFrame(track_ids, columns=['track_ids'])
    tracks_df.drop_duplicates(subset=['track_ids'], keep='first', inplace=True)

    return tracks_df

In [13]:
# 2022 subset 
spotify_22 = pd.DataFrame(music_2022['URLs'])
spotify_22['spotify_URLs'] = spotify_22['URLs'].apply(extract_spotify_urls)
spotify_22 = extract_track_ids(spotify_22)

In [14]:
# 2021 subset 
spotify_21 = pd.DataFrame(music_2021['URLs'])
spotify_21['spotify_URLs'] = spotify_21['URLs'].apply(extract_spotify_urls)
spotify_21 = extract_track_ids(spotify_21)

In [ ]:
spotify_21

In [15]:
# 2020 subset
spotify_20 = pd.DataFrame(music_2020['URLs'])
spotify_20['spotify_URLs'] = spotify_20['URLs'].apply(extract_spotify_urls)
spotify_20 = extract_track_ids(spotify_20)

### Converting Track IDs into Audio Features

In [33]:
# importing spotipy library 
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

In [34]:
SPOTIPY_CLIENT_ID = '861abf04c7d34707989bbfdccbdd1b43'
SPOTIPY_CLIENT_SECRET = '48216550e0d14270aff168fdf962696d'

# optional: 
# SPOTIPY_REDIRECT_URI = 'your-app-redirect-url'

In [35]:
auth_manager = SpotifyClientCredentials(client_id = SPOTIPY_CLIENT_ID, client_secret = SPOTIPY_CLIENT_SECRET)
sp = spotipy.Spotify(auth_manager = auth_manager)

In [19]:
# getting audio features from spotify urls
def get_audio_features(df, sp):
    # Create an empty list to hold the audio features
    audio_features = []

    # Loop through the rows of the DataFrame and get the audio features for each track
    for index, row in df.iterrows():
        track_id = row['track_ids'].split('?')[0]
        uri = f'spotify:track:{track_id}'
        features = sp.audio_features(uri)[0]
        if features:
            audio_features.append(features)

    return audio_features

### 2022 Audio Features `pd.DataFrame`

In [20]:
audio_features_22 = pd.DataFrame(get_audio_features(spotify_22, sp))

In [ ]:
audio_features_22

In [21]:
audio_features_22.to_csv('2022-tweet-audio-feat.csv', sep=',', index=False)

### 2021 Audio Features `pd.DataFrame`

In [22]:
audio_features_21 = pd.DataFrame(get_audio_features(spotify_21, sp))

In [ ]:
audio_features_21

In [23]:
audio_features_21.to_csv('2021-tweet-audio-feat.csv', sep=',', index=False)

### 2020 Audio Features `pd.DataFrame`

In [24]:
audio_features_20 = pd.DataFrame(get_audio_features(spotify_20, sp))

In [ ]:
audio_features_20

In [25]:
audio_features_20.to_csv('2020-tweet-audio-feat.csv', sep=',', index=False)

### 2022 Billboard Audio Features (Hot Singles of 2022)

## Billboard vs. 2022 Twitter Popularity

### Scraping Music Artists from Billboard

In [44]:
# importing necessary libraries 
import requests
from bs4 import BeautifulSoup

In [45]:
def get_billboard_artists(url, num_artists):
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    artist_h3s = soup.find_all('h3', class_='c-title')
    artists = ['#' + element.get_text().strip().replace(' ', '') for element in artist_h3s][:num_artists]
    return artists

In [ ]:
# setting number of artists 
n = 10 # top 10 Billboard artists

### 2022 Billboard Top Artists `list`

In [ ]:
url = 'https://www.billboard.com/charts/year-end/top-artists'
billboard_22 = get_billboard_artists(url, n)

In [ ]:
billboard_22

### 2021 Billboard Top Artists `list`

In [ ]:
url = 'https://www.billboard.com/charts/year-end/2021/top-artists/'
billboard_21 = get_billboard_artists(url, n)

In [ ]:
billboard_21

### 2020 Billboard Top Artists `list`

In [ ]:
url = 'https://www.billboard.com/charts/year-end/2020/top-artists/'
billboard_20 = get_billboard_artists(url, n)

In [ ]:
billboard_20

## 2022 Twitter Billboard Dataset

In [26]:
query = '(open.spotify.com/track AND #billboard)'
start_date = '2022-01-01'
end_date = '2022-12-31'

billboard_2022 = scrape_music_tweets(query, start_date, end_date)
billboard_2022 = music_df(billboard_2022)

<ipython-input-2-5ca9bf2c3f71>:13: FutureWarning: outlinks is deprecated, use links (url attribute) instead
  tweet.outlinks, # url(s)

In [27]:
# removing special characters and dropping url duplicates
billboard_2022['text_clean'] = billboard_2022['text'].apply(clean_text)

In [28]:
billboard_2022 = pd.DataFrame(billboard_2022)
billboard_2022['spotify_URLs'] = billboard_2022['URLs'].apply(extract_spotify_urls)
billboard_2022

,id_str,username,text,date,user_language,URLs,user_id,followers_count,friends_count,user_location,source_device,retweet_count,reply_count,like_count,text_clean,spotify_URLs
0,1605280217895153665,armysusu22,@rize0t7addict RM 'Still Life (with Anderson ....,2022-12-20 19:13:23+00:00,en,"[https://www.youtube.com/user/BANGTANTV, https...",1604471826796908547,24,417,"Cần Thơ, Việt Nam","<a href=""http://twitter.com/download/android"" ...",0,0,0,rize0t7addict rm still life with anderson paak...,[https://open.spotify.com/track/12hD59WtTU92K1...
4,1603841679584559104,ThMLinhNguyn9,@wefightcharts @BTS_twt RM 'Still Life (with A...,2022-12-16 19:57:09+00:00,en,"[https://www.youtube.com/user/BANGTANTV, https...",1513198717989683203,47,754,"Cần Thơ, Việt Nam","<a href=""http://twitter.com/download/android"" ...",0,0,0,wefightcharts bts_twt rm still life with ander...,[https://open.spotify.com/track/12hD59WtTU92K1...
6,1594384310814982144,FreeIsMe3,Now available on #Spotify! \nHear Marcello sin...,2022-11-20 17:36:56+00:00,en,[https://open.spotify.com/track/32gdqUDfS1Qu1u...,1293312140653350913,3421,2490,Tomahawk Rd,"<a href=""https://mobile.twitter.com"" rel=""nofo...",1,2,5,now available on spotify hear marcello sing ou...,[https://open.spotify.com/track/32gdqUDfS1Qu1u...
7,1593331107725836288,maarleneliwag,@SB19HotSongs @SB19Official WYAT (Where You At...,2022-11-17 19:51:53+00:00,en,[https://open.spotify.com/track/1z50Hub2XCsAPW...,555234320,41,335,"Manila, Philippines","<a href=""http://twitter.com/download/iphone"" r...",1,0,1,sb19hotsongs sb19official wyat where you at on...,[https://open.spotify.com/track/1z50Hub2XCsAPW...
26,1592589788103573504,BikerVandal,“Top 20 Tuesday” Week 2: This week we have Ste...,2022-11-15 18:46:09+00:00,en,[https://open.spotify.com/track/5CM4UuQ9Gnd6K2...,1582566560518049793,17,41,"Cincinnati, OH","<a href=""http://twitter.com/download/iphone"" r...",0,1,0,top 20 tuesday week 2 this week we have steve ...,[https://open.spotify.com/track/5CM4UuQ9Gnd6K2...
27,1591871516106526721,annamara_moo,Mamamoo - L.I.E.C is No. 2 at\n#HotTrendingSon...,2022-11-13 19:11:59+00:00,en,[https://open.spotify.com/track/1RNnRdT27xNUTd...,1484672890293428224,31,106,,"<a href=""https://mobile.twitter.com"" rel=""nofo...",1,0,1,mamamoo liec is no 2 at hottrendingsongs billb...,[https://open.spotify.com/track/1RNnRdT27xNUTd...
28,1589833973861330944,LuciMille,So Far Gone by ONE OK ROCK https://t.co/dei3c...,2022-11-08 04:15:31+00:00,en,[https://open.spotify.com/track/1Gwwh7r2kfoRUj...,1243724654264516608,32,67,"Los Angeles, USA","<a href=""http://twitter.com/download/iphone"" r...",1,0,3,so far gone by one ok rock sofargone oneokrock...,[https://open.spotify.com/track/1Gwwh7r2kfoRUj...
29,1588088308483166210,JohnBounceMusic,🆕 John Bounce « #SexyHabits » NEW MIXES #OUTNO...,2022-11-03 08:38:52+00:00,en,[https://open.spotify.com/track/2BbNBRrnjectKE...,2716394720,4551,292,Switzerland,"<a href=""https://mobile.twitter.com"" rel=""nofo...",0,0,1,john bounce sexyhabits new mixes outnow dance...,[https://open.spotify.com/track/2BbNBRrnjectKE...
34,1587941627125182464,thenewno,https://t.co/WEM9wFWfBE @IvoryBlueMusic1 #mp3 ...,2022-11-02 22:56:01+00:00,en,[https://open.spotify.com/track/3bsMSoQ8IOvcRZ...,1571869001147453440,183,328,"Paris, France","<a href=""http://twitter.com/download/iphone"" r...",0,0,0,ivorybluemusic1 mp3 great and terribly catchy...,[https://open.spotify.com/track/3bsMSoQ8IOvcRZ...
35,1575925266412883968,jazz_osaka,https://t.co/VlFcZFUIxO\n\nNow listening \nTit...,2022-09-30 19:07:17+00:00,en,[https://open.spotify.com/track/7ADli7gGUnlG5H...,1520774417600503808,173,125,"Osaka-shi Kita-ku, Osaka","<a href=""http://twitter.com/download/android"" ...",1,0,19,now listening title friday5 paultaylor andnow...,[https://open.spotify.com/track/7ADli7gGUnlG5H...
36,1575922237080600576,A_SeasideJazz,https://t.co/QRS86WFuus\nNow listening \nTitle...,2022-09-30 18:55:15+00:00,en,[https://open.spotify.com/track/13nfozKpyR0FRO...,1514112473825091584,300,257,,"<a href=""http://twitter.com/download/android"" ...",1,0,33,now listening title straight to the point pau...,[https://open.spotify.com/track/13nfozKpyR0FRO...
37,1574169732776960009,ThreeBroth3rs,Summer Time #JohnSalls #music #trending #billb...,2022-09-25 22:51:25+00:00,en,[https://open.spotify.com/track/085d8MgLKt3tqn...,2284347800,2542,2191,"Kentucky, USA","<a href=""http://twitter.com/download/iphone"" r...",0,0,0,summer time johnsalls music trending billboard...,[https://open.spotify.com/track/085d8MgLKt3tqn...
38,1570934628831350784,syanesalvador,Stream Alert❣️❣️❣️\n\nhttps://t.co/1wh2pZPfuR ...,2022-09-17 00:36:16+00:00,en,[https://open.spotify.com/track/0KUn8que34YX4P...,1451832051439603722,0,46,,"<a href=""http://twitter.com/download/android"" ...",0,0,0,stream alert walang bago sa emding billboard f...,[https://open.spotify.com/track/0KUn8que34YX4P...
39,1570736096270782465,BrownAaron14,"We had a bless week, moved up 18 spots on the ...",2022-09-16 11:27:22+00:00,en,[https://open.spotify.com/track/1Vdw6Ef3wFRMJm...,1295380824418918400,989,1848,"White Plains, NY","<a href=""https://mobile.twitter.com"" rel=""nofo...",1,0,2,we had a bless week moved up 18 spots on the s...,[https://open.spotify.com/track/1Vdw6Ef3wFRMJm...
40,1569391199034789888,DJ_Sugar_D,GREAT! My #newrelease „I Came To Jack“ startet...,2022-09-12 18:23:14+00:00,en,[https://open.spotify.com/track/0yrYzmd9bQkmWA...,1444763552565403656,239,69,"Leipzig, Deutschland","<a href=""http://twitter.com/download/iphone"" r...",0,0,2,great my newrelease i came to jack startet thi...,[https://open.spotify.com/track/0yrYzmd9bQkmWA...
41,1563585458029768709,Jazz_St_M,https://t.co/EKeOndiJQZ\nNow Listening \nTitle...,2022-08-27 17:53:17+00:00,en,[https://open.spotify.com/track/13nfozKpyR0FRO...,1510605778557673472,286,223,,"<a href=""http://twitter.com/download/android"" ...",2,0,17,now listening title straight to the point pau...,[https://open.spotify.com/track/13nfozKpyR0FRO...
43,1562257639890817026,GreenhouseEffe8,SEO https://t.co/AA2EAgJbsZ XXX #GreenhouseE...,2022-08-24 01:57:01+00:00,en,[http://open.spotify.com/track/2qsEUCs33QHjRCH...,1527210342194876416,832,3684,,"<a href=""https://mobile.twitter.com"" rel=""nofo...",0,8,5,seo xxx greenhouseeffect brandy spotify is ama...,[https://open.spotify.com/track/2qsEUCs33QHjRC...
44,1561871240314228736,SG_Radio420,@vmas Put these on the #Billboard @BeatsbyDre ...,2022-08-23 00:21:36+00:00,en,[https://open.spotify.com/track/4JKwW0A2OQeAUp...,1560822846955196416,28,79,United States,"<a href=""http://twitter.com/download/android"" ...",0,0,0,vmas put these on the billboard beatsbydre see...,[https://open.spotify.com/track/4JKwW0A2OQeAUp...
45,1560071877258797056,P0P_N4TION,NOW PLAYING 🚨🚨🚨\n@Harry_Styles - As it was\n#A...,2022-08-18 01:11:34+00:00,en,[https://open.spotify.com/track/4Dvkj6JhhA12EX...,1231095719232262144,144,151,,"<a href=""http://twitter.com/download/android"" ...",1,0,5,now playing harry_styles as it was asitwas hot...,[https://open.spotify.com/track/4Dvkj6JhhA12EX...
46,1557967969384284160,yahlaymusic,Just trying to make it in this industry stream...,2022-08-12 05:51:24+00:00,en,[https://open.spotify.com/track/5VrDCttzltIPNh...,1161877715471011840,360,74,"Pittsburgh, PA","<a href=""http://twitter.com/download/android"" ...",0,0,1,just trying to make it in this industry stream...,[https://open.spotify.com/track/5VrDCttzltIPNh...
47,1557414369540984833,CafeMomiji,https://t.co/TFuRT3Y05b\nNow listening \nTitle...,2022-08-10 17:11:35+00:00,en,[https://open.spotify.com/track/7ADli7gGUnlG5H...,1484105180907913216,608,443,,"<a href=""http://twitter.com/download/android"" ...",1,0,15,now listening title friday5 paultaylor andnow...,[https://open.spotify.com/track/7ADli7gGUnlG5H...
48,1557126361525153792,dazelhope,Hey EDM lovers... what's your thought about my...,2022-08-09 22:07:09+00:00,en,[https://open.spotify.com/track/6vvcEBCPCyNLOj...,1365310693411446790,0,0,Indonesia,"<a href=""http://twitter.com/download/android"" ...",0,0,1,hey edm lovers whats your thought about my sin...,[https://open.spotify.com/track/6vvcEBCPCyNLOj...
49,1550926948053880832,lilamon69,2 Million Streams ♥️\nAppreciate all the love ...,2022-07-23 19:32:53+00:00,en,[https://open.spotify.com/track/1wrHQnqj9zHMHr...,712671750086139905,93,83,,"<a href=""http://twitter.com/download/android"" ...",0,0,1,2 million streams appreciate all the love hiph...,[https://open.spotify.com/track/1wrHQnqj9zHMHr...
50,1549970052111376386,WORLDMUSICAWARD,#Billboard names #TaylorSwift's #AllTooWell (1...,2022-07-21 04:10:32+00:00,en,[https://open.spotify.com/track/5enxwA8aAbwZbf...,461688027,496009,60262,,"<a href=""https://mobile.twitter.com"" rel=""nofo...",144,3,768,billboard names taylorswifts alltoowell 10 min...,[https://open.spotify.com/track/5enxwA8aAbwZbf...
51,1547402209901662208,Tsmfotpinc1,Changes Is Now Our Number 2 Song 🙌🔥🔥💪 Thank Yo...,2022-07-14 02:06:50+00:00,en,[https://open.spotify.com/track/54Q4zwGYvNngn8...,1296233759025565696,953,1300,"Austin, TX","<a href=""http://twitter.com/download/iphone"" r...",2,0,6,changes is now our number 2 song thank you rad...,[https://open.spotify.com/track/54Q4zwGYvNngn8...
53,1536647915326021632,LordCockatrice,I just hope @KateBushMusic is a big #Bridgerto...,2022-06-14 09:53:07+00:00,en,[https://open.spotify.com/track/6Fmnn7nFUcyBbi...,1382767302496694280,5,38,,"<a href=""http://twitter.com/download/iphone"" r...",0,0,0,i just hope katebushmusic is a big bridgerton ...,[https://open.spotify.com/track/6Fmnn7nFUcyBbi...
54,1536026173825634305,spacejunkybft,@NoiseHype Hell ya!\n#burntfriedtoast🔥🍳🍞 #radi...,2022-06-12 16:42:32+00:00,en,[https://open.spotify.com/track/6tQqEu2gXkFfSk...,1532996656920023043,89,250,"Los Angeles, CA","<a href=""http://twitter.com/download/iphone"" r...",0,0,1,noisehype hell ya burntfriedtoast radio billbo...,[https://open.spotify.com/track/6tQqEu2gXkFfSk...
55,1535405308692025344,LFTFtheband,wow so honored to share that No Relief has rea...,2022-06-10 23:35:26+00:00,en,[https://open.spotify.com/track/0UcPhk1gMCFeOh...,1214698051782299648,285,426,south philly,"<a href=""http://twitter.com/download/iphone"" r...",7,0,11,wow so honored to share that no relief has rea...,[https://open.spotify.com/track/0UcPhk1gMCFeOh...
56,1533421380636655619,weekly_network,"Listen to ""Berlin, Night Moscow, Vibe"" by #VI...",2022-06-05 12:12:01+00:00,en,[https://open.spotify.com/track/0BzBm5y4mVSXFg...,1067457509357756416,304,66,Sweden,"<a href=""https://mobile.twitter.com"" rel=""nofo...",0,0,2,listen to berlin night moscow vibe by viktorii...,[https://open.spotify.com/track/0BzBm5y4mVSXFg...
58,1532547850609074179,UnitedSongBird,On #June3rd 1972 American🇺🇸 band #CommanderCod...,2022-06-03 02:20:55+00:00,en,[https://open.spotify.com/track/2sZjmnS1BSoc1s...,1207779675507953664,2018,1721,United,"<a href=""https://mobile.twitter.com"" rel=""nofo...",2,0,20,on june3rd 1972 american band commandercody an...,[https://open.spotify.com/track/2sZjmnS1BSoc1s...
59,1530604911964041216,lofi_libra,Hi #SUPERFAMILY We are almost completing the ...,2022-05-28 17:40:22+00:00,en,[http://spoti.fi/3N1qcWS],1518603757994405890,198,611,,"<a href=""http://twitter.com/download/android"" ...",0,0,2,hi superfamily we are almost completing the jo...,[]
60,1526427326778593280,UbiedoD,https://t.co/ZOaPZwr8WP. #Billboard #Billboar...,2022-05-17 05:00:09+00:00,en,[https://open.spotify.com/track/6vbTNyQvMjdkEp...,4313952101,71,328,"Buenos Aires, Argentina","<a href=""http://twitter.com/download/iphone"" r...",0,0,0,billboard billboard music awards,[https://open.spotify.com/track/6vbTNyQvMjdkEp...
61,1524091290660622336,Eisykiewicz,@dimash_official &amp; #TopGunMaverick vibe 💯\...,2022-05-10 18:17:34+00:00,en,[https://open.spotify.com/track/42s7EeGDVPMVg1...,822811330054946816,1109,1315,,"<a href=""http://twitter.com/download/android"" ...",4,0,1,dimash_official amp topgunmaverick vibe dimash...,[https://open.spotify.com/track/42s7EeGDVPMVg1...
68,1520000696078241792,cybmusic2021,Aleyna Tilki - Take It Or Leave It\n\nhttps://...,2022-04-29 11:23:00+00:00,en,[https://open.spotify.com/track/1M65QIDUGHX5ic...,1422098969610670080,48,504,,"<a href=""https://mobile.twitter.com"" rel=""nofo...",0,0,0,aleyna tilki take it or leave it spotify warne...,[https://open.spotify.com/track/1M65QIDUGHX5ic...
69,1516255241125371908,baeksfist,@EXO_Vista @weareoneEXO 🎵: https://t.co/Jz0NRY...,2022-04-19 03:19:54+00:00,en,[https://open.spotify.com/track/3AHV42ObBOu6QZ...,1482672867435114498,180,198,a safe space for firelights,"<a href=""http://twitter.com/download/android"" ...",1,0,0,exo_vista weareoneexo hurdle for billboard hot...,[https://open.spotify.com/track/3AHV42ObBOu6QZ...
72,1514997295129178113,williamscoffees,Daily reminder to stream @whoistillie and buy ...,2022-04-15 16:01:17+00:00,en,[https://open.spotify.com/track/2oSCnKHMNfFggm...,283850977,1296,4218,IsleOfFlightlessBirds,"<a href=""http://twitter.com/download/iphone"" r...",3,1,9,daily reminder to stream whoistillie and buy h...,[https://open.spotify.com/track/2oSCnKHMNfFggm...
74,1513799539198676996,thedarkmusik,New song MR. MACABRE out now!\nListen on Spoti...,2022-04-12 08:41:49+00:00,en,[https://spoti.fi/374K9gp],319409848,4403,162,"Brighton, England","<a href=""http://twitter.com/download/iphone"" r...",2,0,10,new song mr macabre out now listen on spotify ...,[https://spoti.fi/374K9gp]
76,1509551623005106178,prerna_sharma_,Go and listen to NAKED by @finneas and thank m...,2022-03-31 15:22:07+00:00,en,[https://open.spotify.com/track/1aXWzWjj5Lchfm...,2266063454,48,711,,"<a href=""http://twitter.com/download/android"" ...",0,2,3,go and listen to naked by finneas and thank me...,[https://open.spotify.com/track/1aXWzWjj5Lchfm...
77,1503106586172170250,ThisWeeksHT,Pop Music is such a tough field now a days but...,2022-03-13 20:31:51+00:00,en,[https://open.spotify.com/track/1f4UNijJhQt2rS...,1456722828166848513,29,130,,"<a href=""http://twitter.com/download/iphone"" r...",0,0,0,pop music is such a tough field now a days but...,[https://open.spotify.com/track/1f4UNijJhQt2rS...
78,1500090428368076803,JoqueDuJour,"Here's #indierock #sensational #song ""The Cast...",2022-03-05 12:46:43+00:00,en,[https://open.spotify.com/track/68ukxJDpfgxL4u...,3731377402,688,60,"South East, England","<a href=""http://twitter.com/download/android"" ...",0,0,1,heres indierock sensational song the castle it...,[https://open.spotify.com/track/68ukxJDpfgxL4u...
81,1496781665674346496,treceswiftie,Today is a sad day for the European nation and...,2022-02-24 09:38:52+00:00,en,[https://open.spotify.com/track/08fa9LFcFBTcil...,1442954563796049921,138,142,,"<a href=""http://twitter.com/download/android"" ...",0,0,1,today is a sad day for the european nation and...,[https://open.spotify.com/track/08fa9LFcFBTcil...
83,1494795510196097031,Lausolsen,Nr.1 on the Billboards if the big ones promote...,2022-02-18 22:06:36+00:00,en,[https://open.spotify.com/track/0xR1jHC0542lSr...,547447519,1276,5002,Zulu,"<a href=""http://twitter.com/download/android"" ...",0,0,0,nr1 on the billboards if the big ones promote ...,[https://open.spotify.com/track/0xR1jHC0542lSr...
84,1486323744067002374,2point0TnT,"@sparta_distro Fool wit me now...I produce, en...",2022-01-26 13:02:49+00:00,en,[https://open.spotify.com/track/49bnQGBdEpurHl...,94036056,872,2106,"Atlanta, Ga","<a href=""http://twitter.com/download/android"" ...",0,0,1,sparta_distro fool wit me nowi produce enginee...,[https://open.spotify.com/track/49bnQGBdEpurHl...
85,1486277883324686339,Jenn_MobiusMGMT,Happy Release Day @mikelegeremusic! Have a lis...,2022-01-26 10:00:35+00:00,en,[https://spoti.fi/345cGjU],133151405,3815,4935,"ÜT: 43.640462,-79.412864","<a href=""http://twitter.com/download/iphone"" r...",0,0,3,happy release day mikelegeremusic have a liste...,[https://spoti.fi/345cGjU]
86,1486277484878475264,MobiusPr,Happy Release Day @mikelegeremusic! Have a lis...,2022-01-26 09:59:00+00:00,en,[https://spoti.fi/345cGjU],1119013453233102848,35,131,,"<a href=""http://twitter.com/download/iphone"" r...",0,0,2,happy release day mikelegeremusic have a liste...,[https://spoti.fi/345cGjU]
87,1482847541154791426,sickboypoptrash,When something u made out of the Bottom of you...,2022-01-16 22:49:38+00:00,en,[https://open.spotify.com/track/5HjjUFmJMsU9Zy...,971398511022477313,38,246,"Amsterdam, The Netherlands","<a href=""https://mobile.twitter.com"" rel=""nofo...",0,0,0,when something u made out of the bottom of you...,[https://open.spotify.com/track/5HjjUFmJMsU9Zy...
88,1481772841372684293,JustUs4Good,❤️ shaped 🕶 4 LIFE. By my fav @jodnyl on all s...,2022-01-13 23:39:10+00:00,en,[https://open.spotify.com/track/1GcSdb7n29Gb4l...,1476149574301634561,1009,1281,"Philadelphia, PA","<a href=""http://twitter.com/download/iphone"" r...",0,0,1,shaped 4 life by my fav jodnyl on all streami...,[https://open.spotify.com/track/1GcSdb7n29Gb4l...
90,1480964036501987331,thisisapple2763,#Before430 by Mew Suppasit ft Sam Kim on #Hot...,2022-01-11 18:05:15+00:00,en,[https://open.spotify.com/track/6eXHtOGepsKaJ6...,1354794547834834947,34,96,,"<a href=""http://twitter.com/download/android"" ...",0,0,0,before430 by mew suppasit ft sam kim on hottre...,[https://open.spotify.com/track/6eXHtOGepsKaJ6...
91,1480952585892745221,cherrymastah,We moved up 😘😘😘At number 4 #Before430 by Mew S...,2022-01-11 17:19:45+00:00,en,[https://open.spotify.com/track/6eXHtOGepsKaJ6...,1268053855935229952,311,442,Republic of the Philippines,"<a href=""http://twitter.com/download/android"" ...",0,0,1,we moved up at number 4 before430 by mew suppa...,[https://open.spotify.com/track/6eXHtOGepsKaJ6...
93,1479770280759341058,manosseu,Just Another Masterpiece. #theweeknd #dawnfm #...,2022-01-08 11:01:42+00:00,en,[https://open.spotify.com/track/6krYS8KtmNAYyb...,1146508444465319936,43,157,,"<a href=""http://twitter.com/download/iphone"" r...",0,0,1,just another masterpiece theweeknd dawnfm bill...,[https://open.spotify.com/track/6krYS8KtmNAYyb...

In [30]:
billboard_2022.to_csv('2022-tweet-billboard-data.csv', sep=',', index=False)

## 2021 Twitter Billboard Dataset

In [40]:
query = '(open.spotify.com/track AND #billboard)'
start_date = '2021-01-01'
end_date = '2021-12-31'

billboard_2021 = scrape_music_tweets(query, start_date, end_date)
billboard_2021 = music_df(billboard_2021)

billboard_2021['text_clean'] = billboard_2021['text'].apply(clean_text)

billboard_2021 = pd.DataFrame(billboard_2021)
billboard_2021['spotify_URLs'] = billboard_2021['URLs'].apply(extract_spotify_urls)

billboard_2021.to_csv('2021-tweet-billboard-data.csv', sep=',', index=False)

<ipython-input-2-5ca9bf2c3f71>:13: FutureWarning: outlinks is deprecated, use links (url attribute) instead
  tweet.outlinks, # url(s)

## 2020 Twitter Billboard Dataset

In [41]:
query = '(open.spotify.com/track AND #billboard)'
start_date = '2020-01-01'
end_date = '2020-12-31'

billboard_2020 = scrape_music_tweets(query, start_date, end_date)
billboard_2020 = music_df(billboard_2020)

billboard_2020['text_clean'] = billboard_2020['text'].apply(clean_text)

billboard_2020 = pd.DataFrame(billboard_2020)
billboard_2020['spotify_URLs'] = billboard_2020['URLs'].apply(extract_spotify_urls)

billboard_2020.to_csv('2020-tweet-billboard-data.csv', sep=',', index=False)

<ipython-input-2-5ca9bf2c3f71>:13: FutureWarning: outlinks is deprecated, use links (url attribute) instead
  tweet.outlinks, # url(s)

In [31]:
billboard_2022_ids = extract_track_ids(billboard_2022)

In [36]:
billboard_features_22 = pd.DataFrame(get_audio_features(billboard_2022_ids, sp))

In [37]:
billboard_features_22.to_csv('2022-tweet-billboard-audio.csv', sep=',', index=False)

In [42]:
billboard_2021_ids = extract_track_ids(billboard_2021)
billboard_features_21 = pd.DataFrame(get_audio_features(billboard_2021_ids, sp))
billboard_features_21.to_csv('2021-tweet-billboard-audio.csv', sep=',', index=False)

In [43]:
billboard_2020_ids = extract_track_ids(billboard_2020)
billboard_features_20 = pd.DataFrame(get_audio_features(billboard_2020_ids, sp))
billboard_features_20.to_csv('2020-tweet-billboard-audio.csv', sep=',', index=False)

## 2022 Billboard Dataset

### Getting Track URIs

In [ ]:
def get_track_uri(df, sp):
    for i in range(df.shape[0]):
        try:
            track_id = df.loc[i, 'spotify_URLs'].split('/')[-1]
            track_info = sp.track(track_id)
            track_uri = track_info['uri']
            df.at[i, 'track_uri'] = track_uri
        except:
            df.at[i, 'track_uri'] = None
    return df

In [ ]:
billboard100_df = pd.read_csv('2022-billboard-t100-songs.csv')
billboard100_df = pd.DataFrame(billboard100_df['spotify_URLs'])

billboard100_df['spotify_URLs'] = billboard100_df['spotify_URLs'].astype(str)

billboard100_df = get_track_uri(billboard100_df, sp)
billboard100_df

### Getting Audio Features from Track URIs

In [ ]:
def get_audio_features(uris):
    # Initialize list to store audio features for each track
    audio_features = []

    # Loop through each URI and retrieve audio features using the Spotify API
    for uri in uris:
        audio_features.append(sp.audio_features(uri)[0])

    # Convert audio features list to a Pandas DataFrame
    audio_features_df = pd.DataFrame(audio_features)

    return audio_features_df

In [ ]:
billboard100_uris = billboard100_df['track_uri']
billboard100_features = get_audio_features(billboard100_uris)
billboard100_features

In [ ]:
billboard100_features.to_csv('2022-billboard-t100-audio-feat.csv', sep=',', index=False)

## Dataset Balancing

Upon finalizing the touches in the data wrangling/cleaning process, I noticed that the datasets were unbalanced due to the varying amount of rows in each dataset. To prevent bias and to ensure that the dataset is representative, I had to balance the datasets.

## 2022 Twitter Billboard vs. 2022 Billboard Charts

In [ ]:
import random 

# billboard100_features (100 rows)
# billboard_features_22 (46 rows)

# randomly sample of 46 rows from billboard100_features
df_sample = billboard100_features.sample(n = 46, random_state=1)

# combine the sample df and billboard_features_22 to create a balanced df (balanced_billboard_22)
balanced_billboard_22 = pd.concat([billboard_features_22, df_sample], axis=0)

balanced_billboard_22

In [ ]:
balanced_billboard_22.to_csv('2022-balanced-billboard-data.csv', sep=',', index=False)